name: Trigger Vercel Deploy
on:
  push:
    branches:
      - main # Or whatever your main branch is

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸš€ Trigger Vercel Redeploy
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
